"""Causal synchronous TCOM control environment with physical joint execution.

New runs use explicitly specified reference-release rules; archived results are
read by the independent results tools and are never regenerated by substitution.
"""
import numpy as np
from .config import Config
from .contracts import Observation,StepResult
from .geometry import WalkerEphemeris,sample_ground_pool,link_geometry,BeamPlanner
from .channel import Weather,Channel
from .descriptors import cox_parameters,physical_descriptors,ephemeris_void


def first_free_band(occupied,n_subbands,retained=-1):
    """Retain one's valid band; otherwise lowest free index, or -1 if full."""
    if retained>=0: return int(retained)
    used=set(int(x) for x in occupied if x>=0)
    return next((b for b in range(n_subbands) if b not in used),-1)


class Environment:
    def __init__(self,cfg=None,seed=1,episode_id=0):
        self.cfg=cfg or Config(); self.e=self.cfg.environment; self.seed=int(seed); self.episode_id=int(episode_id)
        self.K=self.e['n_users']; self.N=self.e['n_satellites']; self.C=self.e['candidate_cap']
        self.rho,self.beta=cox_parameters(self.e)
        self._prepared=False; self._obs=None
    def reset(self):
        streams=np.random.SeedSequence([self.seed,self.episode_id]).spawn(2)
        self.pool=sample_ground_pool(self.e,np.random.default_rng(streams[0])); self.users=self.pool[:self.K].copy()
        if not self._prepared:
            self.ephemeris=WalkerEphemeris(self.e,self.episode_id); self._prepared=True
        self.weather=Weather(self.e,streams[1]); self.planner=BeamPlanner(self.e,self.pool); self.channel=Channel(self.e)
        self.epoch=0
        self.prev_sat=np.full(self.K,-1,int); self.prev_beam=self.prev_sat.copy(); self.prev_subband=self.prev_sat.copy()
        self.occupancy=np.zeros(self.N,int); self._obs=None; self.peak_state=np.zeros(self.N)
        self._ever_served=np.zeros(self.K,bool)
        self.beam_plan_records=[]; self.beam_plan_history=[]; self.weather_records=[]; self._entry_events=None
        if self.e['descriptor_mode']=='ephemeris': self._prepare_entry_events()
        return self.observe()
    def _prepare_entry_events(self):
        """Sparse exact one-second geometric entries, computed independently of policy."""
        events=[[] for _ in range(self.K)]; prev=None
        threshold=np.deg2rad(self.e['min_elevation_deg'])
        for t,pos in enumerate(self.ephemeris.position):
            vis=link_geometry(self.users,pos)[2]>=threshold
            if prev is not None:
                uu,ss=np.nonzero(vis & ~prev)
                for u,s in zip(uu,ss): events[u].append((t,int(s)))
            prev=vis
        self._entry_events=[np.asarray(x,dtype=int).reshape(-1,2) for x in events]
    def _remaining_visibility(self,users,sats):
        """Find the first invisible one-second sample within the next local pass."""
        if len(users)==0: return np.empty(0,dtype=float)
        lo=np.zeros(len(users),int)
        hi=np.full(len(users),self.e['rst_extension_s'],int)
        radial=self.users[users]/self.e['earth_radius_km']
        elev_cut=np.sin(np.deg2rad(self.e['min_elevation_deg']))
        def visible(offset):
            rays=self.ephemeris.position[self.epoch+offset,sats]-self.users[users]
            sine=np.sum(rays*radial,axis=1)/np.linalg.norm(rays,axis=1)
            return sine>=elev_cut
        if np.any(visible(hi)):
            raise RuntimeError('RST extension is too short to bracket the current visibility exit')
        while np.any(hi-lo>1):
            mid=(lo+hi)//2; keep=visible(mid); active=hi-lo>1
            lo=np.where(active&keep,mid,lo); hi=np.where(active&~keep,mid,hi)
        return hi*self.e['dt']
    def _candidate_band(self,u,s):
        previous_users=np.flatnonzero(self.prev_sat==s)
        current_enabled=self.planner.enabled[self.prev_sat[previous_users],self.prev_beam[previous_users]]
        occupied=self.prev_subband[previous_users[current_enabled]]
        retained=self.prev_subband[u] if self.prev_sat[u]==s else -1
        b=first_free_band(occupied,self.e['n_subbands'],retained)
        return 0 if b<0 else b # reference only when capacity-infeasible
    def observe(self):
        if not hasattr(self,'epoch'): return self.reset()
        if self.epoch>=self.e['horizon']: raise RuntimeError('episode terminated; call reset')
        if self._obs is not None: return self._obs
        e=self.e; pos=self.ephemeris.position[self.epoch]
        distance,unit,elevation=link_geometry(self.users,pos)
        self.visible=elevation>=np.deg2rad(e['min_elevation_deg'])
        old_interval=self.planner.last_interval; self.planner.update(self.epoch,pos)
        if old_interval!=self.planner.last_interval:
            self.beam_plan_history.append((self.epoch,self.planner.targets.copy(),self.planner.enabled.copy()))
            for s,b in zip(*np.nonzero(np.isfinite(self.planner.targets[:,:,0]))):
                self.beam_plan_records.append((self.episode_id,self.epoch,int(s),int(b),*self.planner.targets[s,b].tolist(),bool(self.planner.enabled[s,b])))
        self.weather_records.append((self.epoch,self.weather.rain.copy(),self.weather.blocked.copy()))
        self.channel.update(distance,unit,self.planner.direction(pos),self.planner.enabled,self.weather.attenuation(),above_horizon=elevation>=0.)
        sat=np.full((self.K,self.C),-1,int); beam=sat.copy(); bands=sat.copy()
        sinr=np.zeros((self.K,self.C)); feasible=np.zeros((self.K,self.C),bool)
        rst=np.zeros((self.K,self.C)); c=np.zeros_like(rst); loads=np.zeros_like(rst); broadcast=np.zeros_like(rst)
        p=np.zeros(self.K); counts=self.visible.sum(axis=1); all_candidates=[]
        # Build all visible/enabled pairs first, because p_feas is BEFORE top-K.
        for u in range(self.K):
            ss=np.flatnonzero(self.visible[u]); enabled=self.planner.enabled[ss]
            local_s,bb=np.nonzero(enabled); ss=ss[local_s]
            bs=np.array([self._candidate_band(u,int(s)) for s in ss],int)
            all_candidates.append((ss,bb,bs))
        length=[len(x[0]) for x in all_candidates]
        uu=np.repeat(np.arange(self.K),length)
        ss=np.concatenate([x[0] for x in all_candidates]); bb=np.concatenate([x[1] for x in all_candidates]); bs=np.concatenate([x[2] for x in all_candidates])
        gammas=self.channel.sinr(uu,ss,bb,bs,self.prev_sat,self.prev_beam,self.prev_subband)[0] if len(uu) else np.empty(0)
        cursor=0
        for u,(ss,bb,bs) in enumerate(all_candidates):
            g=gammas[cursor:cursor+len(ss)]; cursor+=len(ss)
            plus=self.occupancy[ss]+1-(ss==self.prev_sat[u])
            ok=(g>=10**(e['sinr_threshold_db']/10.))&(plus<=e['capacity'])
            p[u]=len(np.unique(ss[ok]))/counts[u] if counts[u] else 0.
            order=np.lexsort((bb,ss,-g))[:self.C]
            current=np.flatnonzero((ss==self.prev_sat[u])&(bb==self.prev_beam[u])&ok)
            if len(current) and current[0] not in order:
                if len(order)<self.C: order=np.append(order,current[0])
                else: order[-1]=current[0]
            n=len(order)
            sat[u,:n]=ss[order]; beam[u,:n]=bb[order]; bands[u,:n]=bs[order]
            sinr[u,:n]=g[order]; feasible[u,:n]=ok[order]
            loads[u,:n]=plus[order]; broadcast[u,:n]=self.occupancy[ss[order]]/e['capacity']
            if self.prev_sat[u]>=0:
                c[u,:n]=np.where(ss[order]!=self.prev_sat[u],e['c_intersatellite'],np.where(bb[order]!=self.prev_beam[u],e['c_interbeam'],0.))
        valid=sat>=0; ugrid=np.broadcast_to(np.arange(self.K)[:,None],sat.shape)
        # Many beams of the same satellite share the exact RST.
        unique,pair_inv=np.unique(np.stack([ugrid[valid],sat[valid]],axis=1),axis=0,return_inverse=True)
        if len(unique): rst[valid]=self._remaining_visibility(unique[:,0],unique[:,1])[pair_inv]
        common=np.full(self.K,e['dt'])
        old_valid=(self.prev_sat>=0)
        old_valid[old_valid]&=self.visible[np.flatnonzero(old_valid),self.prev_sat[old_valid]]
        us=np.flatnonzero(old_valid)
        if len(us): common[us]=self._remaining_visibility(us,self.prev_sat[us])
        z,survival,rate=physical_descriptors(p,rst,common,sinr,broadcast,c,self.rho,self.beta,e['t_ref_s'])
        obs_rate=e['bandwidth_mhz']*np.log2(1.+sinr)
        _,wh,wl,wr=self.cfg.weights
        analytic=wr*obs_rate/e['r_ref_mbps']-wh*c-wl*loads/e['capacity']
        analytic[~valid]=0.; z[~valid]=0.; survival[~valid]=0.
        eph_z=eph_survival=None
        if self.e['descriptor_mode']=='ephemeris':
            eph_z=z.copy(); eph_survival=np.zeros_like(survival)
            for u,events in enumerate(self._entry_events):
                if len(events):
                    active=(events[:,0]>self.epoch)&(~self.visible[u,events[:,1]])
                    offsets=np.sort(events[active,0]-self.epoch)
                else: offsets=np.empty(0,int)
                ncommon=np.searchsorted(offsets,common[u],side='right')
                eph_z[u,:,0]=ephemeris_void(p[u],ncommon)
                eph_z[u,:,1]=np.log1p(p[u]*ncommon/common[u]*e['t_ref_s'])
                own=np.searchsorted(offsets,rst[u],side='right')
                eph_survival[u]=ephemeris_void(p[u],own)
            eph_z[~valid]=0.; eph_survival[~valid]=0.
        reasons=np.full(sat.shape,'padded',dtype='<U32')
        for u,j in zip(*np.nonzero(valid)):
            s=sat[u,j]
            if self.prev_sat[u]==s and self.prev_subband[u]>=0: reasons[u,j]='retained'
            else:
                prior=np.flatnonzero(self.prev_sat==s)
                active_prior=prior[self.planner.enabled[self.prev_sat[prior],self.prev_beam[prior]]]
                full=len(np.unique(self.prev_subband[active_prior]))>=e['n_subbands']
                reasons[u,j]='full_satellite_reference' if full else 'lowest_free'
        self._obs=Observation(self.epoch,sat,beam,feasible,z,analytic,survival,self.prev_sat.copy(),self.prev_beam.copy(),self.rho,self.beta,p,rst,sinr,bands,obs_rate,loads,self.prev_subband.copy(),common,rate,counts,eph_z,eph_survival,reasons)
        return self._obs
    def step(self,request_slots,scores=None):
        obs=self.observe(); e=self.e
        request=np.asarray(request_slots,dtype=int)
        if request.shape!=(self.K,): raise ValueError(f'request_slots must have shape {(self.K,)}')
        if np.any((request< -1)|(request>=self.C)): raise ValueError('request slot out of range')
        nonempty=request>=0; us=np.flatnonzero(nonempty)
        if np.any(~obs.feasible[us,request[us]]): raise ValueError('request selects an infeasible or padded slot')
        if np.any(~nonempty & obs.feasible.any(axis=1)): raise ValueError('empty request allowed only for an empty decision set')
        req_s=np.full(self.K,-1,int); req_b=req_s.copy(); priority=np.zeros(self.K)
        req_s[us]=obs.sat_id[us,request[us]]; req_b[us]=obs.beam_id[us,request[us]]; priority[us]=obs.sinr[us,request[us]]
        attempt=(self.prev_sat>=0)&nonempty&((req_s!=self.prev_sat)|(req_b!=self.prev_beam))
        current=obs.current&obs.feasible
        reserve=current.any(axis=1)
        tentative_s=np.full(self.K,-1,int); tentative_b=tentative_s.copy(); tentative_band=tentative_s.copy()
        reserved_by_sat=[set() for _ in range(self.N)]
        used=[set() for _ in range(self.N)]
        for u in np.flatnonzero(reserve):
            s=self.prev_sat[u]; reserved_by_sat[s].add(int(u)); used[s].add(int(self.prev_subband[u]))
            tentative_s[u]=s; tentative_b[u]=self.prev_beam[u]; tentative_band[u]=self.prev_subband[u]
        admitted=np.zeros(self.K,bool); rejected=np.zeros(self.K,bool)
        # Existing same-satellite changes have priority even when the old beam is infeasible.
        # Their previous orthogonal band remains unique and consumes no extra slot.
        same_satellite=nonempty & (self.prev_sat>=0) & (req_s==self.prev_sat)
        for u in np.flatnonzero(same_satellite):
            s=req_s[u]; band=int(self.prev_subband[u])
            if band<0: raise RuntimeError('existing association has no subband')
            used[s].add(band); tentative_s[u]=s; tentative_b[u]=req_b[u]; tentative_band[u]=band; admitted[u]=True
        # Globally sorting preserves each satellite's target SINR/UE-index order.
        order=np.lexsort((np.arange(self.K),-priority))
        for u in order:
            if not nonempty[u] or admitted[u]: continue
            s,b=req_s[u],req_b[u]
            if reserve[u] and s==self.prev_sat[u]:
                tentative_b[u]=b; admitted[u]=True
            elif len(used[s])<e['capacity']:
                band=first_free_band(used[s],e['n_subbands'])
                if band<0: raise RuntimeError('capacity/subband invariant failed')
                used[s].add(band); tentative_s[u]=s; tentative_b[u]=b; tentative_band[u]=band; admitted[u]=True
                # The source reservation remains unavailable until epoch end.
            else: rejected[u]=True
        active=np.flatnonzero(tentative_s>=0)
        check_sinr=np.zeros(self.K); signal=np.zeros(self.K); interference=np.zeros(self.K)
        if len(active):
            vals=self.channel.sinr(active,tentative_s[active],tentative_b[active],tentative_band[active],tentative_s,tentative_b,tentative_band)
            check_sinr[active],signal[active],interference[active]=vals
        pass_check=np.zeros(self.K,bool)
        pass_check[active]=self.visible[active,tentative_s[active]] & self.planner.enabled[tentative_s[active],tentative_b[active]] & (check_sinr[active]>=10**(e['sinr_threshold_db']/10.))
        executed_s=np.where(pass_check,tentative_s,-1); executed_b=np.where(pass_check,tentative_b,-1); executed_band=np.where(pass_check,tentative_band,-1)
        active_final=np.flatnonzero(pass_check); final_sinr=np.zeros(self.K); final_signal=np.zeros(self.K); final_interference=np.zeros(self.K)
        if len(active_final):
            vals=self.channel.sinr(active_final,executed_s[active_final],executed_b[active_final],executed_band[active_final],executed_s,executed_b,executed_band)
            final_sinr[active_final],final_signal[active_final],final_interference[active_final]=vals
        rate=e['bandwidth_mhz']*np.log2(1.+final_sinr)
        occupancy=np.bincount(executed_s[pass_check],minlength=self.N)
        c_exec=np.zeros(self.K)
        prior=pass_check&(self.prev_sat>=0)
        c_exec[prior]=np.where(executed_s[prior]!=self.prev_sat[prior],e['c_intersatellite'],np.where(executed_b[prior]!=self.prev_beam[prior],e['c_interbeam'],0.))
        user_load=np.zeros(self.K); user_load[pass_check]=occupancy[executed_s[pass_check]]/e['capacity']
        wo,wh,wl,wr=self.cfg.weights
        cost=wo*(~pass_check)+wh*c_exec+wl*user_load-wr*rate/e['r_ref_mbps']
        failure=attempt&~pass_check
        executed_ho=pass_check&(self.prev_sat>=0)&((executed_s!=self.prev_sat)|(executed_b!=self.prev_beam))
        nonattempt_out=~pass_check&~attempt
        retain_request=(self.prev_sat>=0)&(req_s==self.prev_sat)&(req_b==self.prev_beam)
        empty_source=self.prev_sat<0
        info=dict(epoch=self.epoch,candidate_subband=obs.candidate_subband.copy(),candidate_subband_reason=obs.candidate_subband_reason.copy(),visible_satellite_count=obs.visible_satellite_count.copy(),
            candidate_satellite=obs.sat_id.copy(),candidate_beam=obs.beam_id.copy(),candidate_feasible=obs.feasible.copy(),candidate_sinr=obs.sinr.copy(),
            request_sat=req_s.copy(),request_beam=req_b.copy(),
            previous_sat=self.prev_sat.copy(),previous_beam=self.prev_beam.copy(),admitted=admitted,rejected=rejected,
            reserved_source=reserve,same_satellite_priority=same_satellite,tentative_sat=tentative_s,tentative_beam=tentative_b,tentative_subband=tentative_band,
            check_sinr=check_sinr,execution_check_failed=(tentative_s>=0)&~pass_check,final_sinr=final_sinr,
            signal_w=final_signal,interference_w=final_interference,noise_w=self.channel.noise_w,
            executed_handover=executed_ho,normalized_executed_load=user_load,
            outage_nonattempt=nonattempt_out,outage_nonattempt_retention=nonattempt_out&retain_request,
            outage_nonattempt_access=nonattempt_out&empty_source&nonempty,
            outage_nonattempt_empty_request=nonattempt_out&~nonempty,
            outage_source_lost_empty_decision=nonattempt_out&(self.prev_sat>=0)&~nonempty,
            outage_initial_access=nonattempt_out&empty_source&~self._ever_served,
            outage_reacquisition=nonattempt_out&empty_source&self._ever_served,
            visibility=self.visible.copy(),rain_state=self.weather.rain.copy(),blocked_state=self.weather.blocked.copy())
        self._ever_served|=pass_check
        self.prev_sat=executed_s.copy(); self.prev_beam=executed_b.copy(); self.prev_subband=executed_band.copy(); self.occupancy=occupancy
        self.peak_state=e['peak_smoothing']*self.peak_state+(1-e['peak_smoothing'])*occupancy/e['capacity']
        info['smoothed_load']=self.peak_state.copy()
        self.epoch+=1; self._obs=None
        if self.epoch<e['horizon']:
            self.weather.advance(); next_obs=self.observe()
        else: next_obs=None
        return StepResult(next_obs,-cost,executed_s,executed_b,executed_band,rate,cost,c_exec,occupancy,attempt,failure,info,request.copy())

    def export_exogenous(self,path):
        """Save portable geometry, observed weather, and the complete planned beam trace.

        Geometry includes the RST extension; weather/beam records cover the epochs
        actually observed. The archive is an implementation output, not a rewrite
        of any historical experiment file.
        """
        from pathlib import Path
        import json
        if not hasattr(self,'epoch'): self.reset()
        path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
        rain=np.stack([x[1] for x in self.weather_records])
        block=np.stack([x[2] for x in self.weather_records])
        norm=np.linalg.norm(self.users,axis=1)
        lat=np.rad2deg(np.arcsin(self.users[:,2]/norm))
        lon=np.rad2deg(np.arctan2(self.users[:,1],self.users[:,0]))
        plan=np.asarray(self.beam_plan_records,dtype=float).reshape(-1,8)
        np.savez_compressed(path,episode_id=np.array(self.episode_id),environment_seed=np.array(self.seed),
            start_utc=np.array(self.ephemeris.start.isoformat()),config_json=np.array(json.dumps(self.cfg.to_dict())),
            user_ecef_km=self.users,user_latitude_deg=lat,user_longitude_deg=lon,planning_points_ecef_km=self.pool,
            satellite_ecef_km=self.ephemeris.position,geometry_epoch_s=np.arange(len(self.ephemeris.position))*self.e['dt'],
            weather_epoch_s=np.array([x[0] for x in self.weather_records])*self.e['dt'],rain=rain,blocked=block,
            beam_interval_start_s=np.array([x[0] for x in self.beam_plan_history])*self.e['dt'],
            beam_target_ecef_km=np.stack([x[1] for x in self.beam_plan_history]),beam_enabled=np.stack([x[2] for x in self.beam_plan_history]),
            beam_plan=plan,beam_plan_columns=np.array(['episode_id','interval_start_s','satellite_id','beam_id','target_x_km','target_y_km','target_z_km','enabled']))
        return path
