"""Stable entry points for the paper-protocol implementation."""

from .dataset import (
    PAPER_DATASET_KIND,
    PAPER_DATASET_SCHEMA_VERSION,
    PaperEpisodeDataset,
    build_paper_dataset,
    generate_sharded_paper_dataset,
    load_paper_dataset,
    save_paper_dataset,
)
from .evaluation import (
    DEFAULT_PAIRED_MODES,
    EVALUATION_SCHEMA_VERSION,
    load_frozen_model,
    run_paper_evaluation,
    save_evaluation_bundle,
)
from .models import (
    PAPER_METHODS,
    build_paper_model,
    normalize_paper_method,
    parameter_count,
    resolved_model_config,
)
from .runtime_baselines import (
    RUNTIME_BASELINE_KINDS,
    BigMLP,
    EdgeAttn,
    TempTrans,
    build_runtime_baseline,
)
from .snapshot import (
    SNAPSHOT_SI_SCORE_GRID,
    SNAPSHOT_SI_SELECTED_SCORE_WEIGHTS,
    SnapshotFixedRankController,
    SnapshotLossWeights,
    SnapshotMarginConfig,
    SnapshotOutput,
    SnapshotPolicyConfig,
    SnapshotScoreWeights,
    snapshot_si_policy_config,
)
from .snapshot_data import (
    SNAPSHOT_DATASET_KIND,
    SNAPSHOT_EDGE_FEATURE_NAMES,
    SNAPSHOT_FEATURE_CONTRACT_VERSION,
    SNAPSHOT_NODE_FEATURE_NAMES,
    ConstantSnapshotInitializer,
    SnapshotControlInput,
    SnapshotEpisodeDataset,
    SnapshotFeatureConfig,
    generate_sharded_snapshot_dataset,
)
from .snapshot_evaluation import (
    SnapshotClosedLoopResult,
    SnapshotEvaluationMode,
    SnapshotModelProvider,
    run_snapshot_closed_loop,
)
from .snapshot_config import (
    ResolvedSnapshotPipeline,
    SnapshotTrainingSettings,
    resolve_snapshot_pipeline,
)
from .snapshot_metrics import (
    evaluate_snapshot_pair,
    snapshot_shrink_jump_ratios,
    snapshot_as_canonical_closed_loop,
)
from .snapshot_models import (
    SNAPSHOT_METHODS,
    build_snapshot_model,
    normalize_snapshot_method,
    resolved_snapshot_model_config,
)
from .snapshot_training import SnapshotTrainingAdapter
from .training import (
    PAPER_TRAINER_SCHEMA_VERSION,
    FitResult,
    PaperTrainer,
    PaperTrainingConfig,
    ScalarSchedule,
    build_multistep_weights,
)

__all__ = [
    "DEFAULT_PAIRED_MODES",
    "EVALUATION_SCHEMA_VERSION",
    "FitResult",
    "PAPER_DATASET_KIND",
    "PAPER_DATASET_SCHEMA_VERSION",
    "PAPER_METHODS",
    "PAPER_TRAINER_SCHEMA_VERSION",
    "RUNTIME_BASELINE_KINDS",
    "SNAPSHOT_DATASET_KIND",
    "SNAPSHOT_EDGE_FEATURE_NAMES",
    "SNAPSHOT_FEATURE_CONTRACT_VERSION",
    "SNAPSHOT_METHODS",
    "SNAPSHOT_NODE_FEATURE_NAMES",
    "SNAPSHOT_SI_SCORE_GRID",
    "SNAPSHOT_SI_SELECTED_SCORE_WEIGHTS",
    "BigMLP",
    "EdgeAttn",
    "PaperEpisodeDataset",
    "PaperTrainer",
    "PaperTrainingConfig",
    "ConstantSnapshotInitializer",
    "SnapshotClosedLoopResult",
    "SnapshotControlInput",
    "SnapshotEpisodeDataset",
    "SnapshotEvaluationMode",
    "SnapshotFeatureConfig",
    "SnapshotFixedRankController",
    "SnapshotLossWeights",
    "SnapshotMarginConfig",
    "SnapshotModelProvider",
    "SnapshotOutput",
    "SnapshotPolicyConfig",
    "ResolvedSnapshotPipeline",
    "SnapshotScoreWeights",
    "SnapshotTrainingAdapter",
    "SnapshotTrainingSettings",
    "ScalarSchedule",
    "TempTrans",
    "build_multistep_weights",
    "build_paper_dataset",
    "build_paper_model",
    "build_runtime_baseline",
    "build_snapshot_model",
    "generate_sharded_paper_dataset",
    "generate_sharded_snapshot_dataset",
    "evaluate_snapshot_pair",
    "load_frozen_model",
    "load_paper_dataset",
    "normalize_paper_method",
    "normalize_snapshot_method",
    "parameter_count",
    "resolved_model_config",
    "resolved_snapshot_model_config",
    "resolve_snapshot_pipeline",
    "run_paper_evaluation",
    "run_snapshot_closed_loop",
    "save_evaluation_bundle",
    "save_paper_dataset",
    "snapshot_si_policy_config",
    "snapshot_as_canonical_closed_loop",
    "snapshot_shrink_jump_ratios",
]
